name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
          chromedriver-version: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Selenium tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
          export CHROME_PATH=$(which google-chrome)
          export CHROMEDRIVER_PATH=$(which chromedriver)
          pytest -v test_busqueda.py